version: '3.7'

networks:
  gitlab:

services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    ports:
      - "8090:80"
      - "222:22"
    restart: always
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    networks:
      - gitlab